application: my-app
version: 1
runtime: python
api_version: 1

derived_file_type:
- python_precompiled

handlers:
- url: /(robots\.txt|favicon\.ico)
  static_files: templates/themes/default/static/\1
  upload: static/(.*)

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /_ah/queue/deferred
  script: main.py
  login: admin

- url: /admin/static
  static_dir: templates/admin/static/

- url: /static/([^/]+)/(.*)
  static_files: templates/themes/\1/static/\2
  upload: templates/themes/[^/]+/static/.*

- url: /.*
  script: main.py
